version: "3.9"
networks:
  roboshop:
    driver: bridge
# volumes:
# # This is equivalent to docker volume create [volume-name]. these are named volumes
#   mysql:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /mysql
#   redis:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /redis
#   rabbitmq:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /rabbitmq
#   mongodb:
#     driver: local
#     driver_opts:
#       o: bind
#       type: none
#       device: /mongodb
services:
  web:
    image: gbalakrishna/web:v.1.0.1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - mysql
    - shipping
  mongodb:
    image: gbalakrishna/mongodb:v.0.0.1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: gbalakrishna/catalogue:v.0.0.1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: gbalakrishna/redis:v.0.0.1
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: gbalakrishna/user:v.0.0.1
    container_name: user
    depends_on:
    - mongodb
    - redis
  cart:
    image: gbalakrishna/cart:v.0.0.1
    container_name: cart
    depends_on:
    - redis
    - catalogue
  mysql:
    image: gbalakrishna/mysql:v.0.0.1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: gbalakrishna/shipping:v.0.0.1
    container_name: shipping
    depends_on:
    - mysql
  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  payment:
    image: gbalakrishna/payment:v.0.0.1
    container_name: payment
    depends_on:
    - rabbitmq

